version: "3.7"

services:
    tomcat:
        restart: always
        build:
            context: ./java
            target: tomcat
            args:
                - USER
        ports:
            - "8080:8080"
        depends_on:
            - mysql
    mysql:
        restart: always
        build:
            context: ./java
            target: mysql
            args:
                - USER
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
