version: "3.7"

services:
    tomcat:
        restart: always
        build:
            context: ./java
            target: tomcat
        ports:
            - "8080:8080"
        depends_on:
            - mysql
    mysql:
        restart: always
        build:
            context: ./java
            target: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=Tupperware
